# Generated by Django 5.1 on 2024-08-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0002_stock_categories'),
        ('stock_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_review',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_review', to='equities.stock'),
        ),
    ]
