# Generated by Django 5.1 on 2024-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol, e.g., AAPL', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the company, e.g., Apple Inc.', max_length=100)),
                ('exchange', models.CharField(help_text='Stock exchange, e.g., NASDAQ', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price of the stock', max_digits=10)),
                ('volume', models.IntegerField(help_text='Trading volume of the stock')),
                ('market_cap', models.BigIntegerField(help_text='Market capitalisation of the company')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Price-to-Earnings ratio', max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Dividend yield in percentage', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the company', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the stock information was last updated')),
            ],
        ),
    ]
