# Generated by Django 5.1 on 2024-08-28 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(help_text='Stock ticker symbol, e.g., AAPL', max_length=10, unique=True)),
                ('company_name', models.CharField(help_text='Full name of the company, e.g., Apple Inc.', max_length=100)),
                ('trade_date', models.DateTimeField(help_text='The date when the stock was traded')),
                ('quantity', models.IntegerField(help_text='Number of shares purchased')),
                ('share_price', models.DecimalField(decimal_places=2, help_text='Price per share at the time of purchase', max_digits=10)),
                ('new_share_price', models.DecimalField(decimal_places=2, help_text='New Price per share at current time', max_digits=10)),
                ('brokerage_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Any brokerage fees associated with the purchase', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional information relevant to the stock', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the stock information was last updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
