# Generated by Django 5.1 on 2024-08-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='new_share_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='New Price per share at current time', max_digits=10, null=True),
        ),
    ]
