# Generated by Django 5.1 on 2024-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories that the stock belongs to', related_name='stocks', to='category.category'),
        ),
    ]
