# Generated by Django 5.1 on 2024-08-22 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone  # Import timezone to use in the default value


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0003_stock_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='company_code',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AddField(
            model_name='stock',
            name='brokerage_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Any brokerage fees associated with the purchase', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of shares purchased'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=1.00, help_text='Price per share at the time of purchase', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=1.00, help_text='Total investment amount', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='trade_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the stock was traded'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information relevant to the stock', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
