# Generated by Django 5.1 on 2024-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0004_rename_symbol_stock_company_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='total_investment',
        ),
        migrations.AddField(
            model_name='stock',
            name='new_share_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='New Price per share at current time', max_digits=10),
            preserve_default=False,
        ),
    ]
